### ISSUE TITLE
Details tag with tables or table syntax not correctly rendered after modifying AST and converting back to Markdown

### ISSUE THREAD

**Issue by niravbhuva99** [syntax-tree/mdast-util-mdx#1]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

I have tested this issue using the latest version of the relevant packages.

### Link to runnable example

[runnable example](https://github.com/niravbhuva99/mdx)

### Steps to reproduce

1. Include a table or table syntax within a `<details>` tag in Markdown.
2. Convert Markdown to AST.
3. Make modifications to the AST.(optional)
4. Convert the modified AST back to Markdown.
5. Observe that the `<details>` tag with the table or table syntax does not render correctly.

When modifying the Abstract Syntax Tree (AST) and converting it back to Markdown, the `<details>` tag containing either tables or table syntax is not rendered correctly. This issue arises specifically when converting Markdown to AST, making modifications, and then converting back to Markdown. The `<details>` tag fails to render as expected in the presence of  table syntax within it.

### Expected behavior

The `<details>` tag with the table or table syntax should render properly after converting the modified AST back to Markdown.

## Behavior with Table Syntax

<img width="1670" alt="Screenshot 2024-03-02 at 22 13 21" src="https://github.com/syntax-tree/mdast-util-mdx/assets/91559189/180a8923-6104-4ca8-aa6f-dd2a247ad0e3">

## Behavior with Table Syntax Inside Details Tag
<img width="1670" alt="Screenshot 2024-03-02 at 22 10 40" src="https://github.com/syntax-tree/mdast-util-mdx/assets/91559189/ee01cd50-a9dc-40ac-a133-75ee770d1dca">

### Affected runtime and version

node@21.5.0

### Affected package manager and version

 "micromark-extension-mdxjs": "^3.0.0",     "mdast-util-mdx": "^3.0.0",     "mdast-util-from-markdown": "^2.0.0",     "mdast-util-to-markdown": "^2.1.0",     "@mdx-js/mdx": "^3.0.1",     "@mdx-js/mdxast": "^1.1.1"

### Affected OS and version

macOs

**Comment by wooorm** [comment]
Hey!

I think your previewer is wrong. You use a markdown previewer. It doesn’t render MDX 2+ properly.

`@mdx-js/mdxast` is ancient and archived and deprecated, don’t use it.

Your example looks fine. Both the input and output MDX are perfect.

Your screenshots don’t include `details`?
And what are you modifying? I don’t see anything in your linked example doing that.

**Comment by niravbhuva99** [comment]
Thank you for your reply 

I changed the previewer, but the result remains the same. I want the Markdown to render the same result before and after the modification. The modification involves changing the link node. The modification process itself seems to be working fine; however, the issue lies in the Markdown rendering after converting the modified AST back to Markdown. 

### Markdown renders before the modification
<img width="1670" alt="Screenshot 2024-03-03 at 16 20 50" src="https://github.com/syntax-tree/mdast-util-mdx/assets/91559189/8d4f9a05-1bd5-4d4c-aa0e-c3d43fdd47db">


### Markdown renders after the modification
<img width="1670" alt="Screenshot 2024-03-03 at 16 22 39" src="https://github.com/syntax-tree/mdast-util-mdx/assets/91559189/7e5b4429-f712-4546-b47a-4f8cb0da40f4">

One observation is that it adds an extra line.

**Comment by wooorm** [comment]
> I want the Markdown [...]

> [...] back to Markdown

This project isn’t about markdown. This is MDX. There is a real difference. Don’t use MDX things if you want markdown.

> [...] to render the same result before and after the modification.

ASTs don’t work like that. ASTs are not CSTs.

> The modification process itself seems to be working fine; 

Which one? Your code does not modify.

> the issue lies in the Markdown rendering after converting the modified AST back to Markdown.

That is not an issue. That’s how MDX works. You’re asking about XY problems and not providing code. Please explain your actual question. Please provide more info.

[![IMG_4335](https://images.prismic.io/sketchplanations/685157ae-ec27-4e9b-9749-eb689a8c65c5_SP+854+-+The+XY+problem.png?auto=format%2Ccompress&fit=max&w=3840&q=50)](https://sketchplanations.com/the-xy-problem)

**Comment by niravbhuva99** [comment]
How can I convert MDX to AST and AST to MDX?

Is this the right method?
<img width="714" alt="Screenshot 2024-03-03 at 17 03 23" src="https://github.com/syntax-tree/mdast-util-mdx/assets/91559189/ab8182f5-0542-4e59-a229-7d276187ec34">

**Comment by wooorm** [comment]
Yes. Use .mdx as an extension though

**Comment by niravbhuva99** [comment]
Now please [clone](https://github.com/niravbhuva99/mdx) this repository and run 'npm install'. After that, execute the 'index.js' file. This will generate the 'processes.mdx' file. Open the file with MDX Preview

**Comment by ChristianMurphy** [comment]
@niravbhuva99 put your example in a sandbox.
Like https://stackblitz.com/ or https://codesandbox.io/

Nobody wants to run an unvetted executable on their machine, it's a security nightmare.

**Comment by niravbhuva99** [comment]
[here is the example](https://codesandbox.io/p/devbox/mdx-s48298?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltbtoe6h00063b6hp05nrq88%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltbtoe6g00023b6hus2eqpyc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltbtoe6g00043b6hfpx7qt6p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltbtoe6g00053b6hcvnpturs%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltbtoe6g00023b6hus2eqpyc%2522%253A%257B%2522id%2522%253A%2522cltbtoe6g00023b6hus2eqpyc%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltbtoe6g00053b6hcvnpturs%2522%253A%257B%2522id%2522%253A%2522cltbtoe6g00053b6hcvnpturs%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltbtoe6g00043b6hfpx7qt6p%2522%253A%257B%2522id%2522%253A%2522cltbtoe6g00043b6hfpx7qt6p%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltbtoe6g00033b6hohwae8d3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltbtoe6g00033b6hohwae8d3%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ChristianMurphy** [comment]
@niravbhuva99 you are generating a `.md` extension instead of `.mdx`.
Other than the extension, the generated file looks valid and it renders the same in https://mdxjs.com/playground/ as the original file did.

**Comment by wooorm** [comment]
You're asking about a previewer. I don't know this previewer. This tools seems broken. If it's broken, ask the folks working on that tool. For us here: why do you care about some random preview tool? What do you *actually* want to do? MDX, markdown? What is your root problem?

**Comment by niravbhuva99** [comment]
@ChristianMurphy  Do you know which previewer the MDXjs playground uses?

**Comment by ChristianMurphy** [comment]
@niravbhuva99 the MDX website uses MDX to render the preview https://github.com/mdx-js/mdx/blob/8f754f707207915bd34c3af8f9064e367c125a58/docs/_asset/editor.jsx

That doesn't answer the question what are _you_ using and trying to do?

**Comment by niravbhuva99** [comment]
I'm currently working with netlify-cms. My aim is to be able to preview MDX components embedded in my pages directly within Netlify CMS. I am also modifying the link nodes and then converting them back to MDX.  It seems that after this modification, some of the MDX content does not render as expected.

**Comment by niravbhuva99** [comment]
I am using a package called [netlify-cms-widget-mdx](https://github.com/karolis-sh/gatsby-mdx/tree/main/packages/netlify-cms-widget-mdx).

**Comment by ChristianMurphy** [comment]
It is broken because `netlify-cms-widget-mdx` uses `mdx-scoped-runtime` (https://github.com/karolis-sh/gatsby-mdx/blob/80de7cbdb1b514ade5266da086ab5490d3441ee4/packages/netlify-cms-widget-mdx/package.json#L26).
`mdx-scoped-runtime` uses MDX version 0 (alpha and unmaintained for years, https://github.com/karolis-sh/gatsby-mdx/blob/80de7cbdb1b514ade5266da086ab5490d3441ee4/packages/mdx-scoped-runtime/package.json#L26), we're on version 3 currently.

Ask `netlify-cms-widget-mdx` to update to use the latest MDX.
